### ISSUE TITLE
Experimental dynamics RK4 Butcher tableau typo

### ISSUE THREAD

**Issue by Matematija** [netket/netket#1056]
Hi,

I was going through your new experimental ODE integrator code and I think I noticed a typo in one of the predefined Butcher tableaus for the `RK4` solver. You have:

```python
bt_rk4  = TableauRKExplicit(
                order = (4,),
                a = jnp.array([[0,   0,   0,   0],
                               [1/2, 0,   0,   0],
                               [0,   1/2, 0,   0],
                               [0,   0,   1,   1]], dtype=default_dtype),
                b = jnp.array( [1/6,  1/3,  1/3,  1/6], dtype=default_dtype),
                c = jnp.array( [0, 1/2, 1/2, 1], dtype=default_dtype),
                c_error = None,
                )
```

while I believe that the correct tableau should be

```python
bt_rk4  = TableauRKExplicit(
                order = (4,),
                a = jnp.array([[0,   0,   0,   0],
                               [1/2, 0,   0,   0],
                               [0,   1/2, 0,   0],
                               [0,   0,   1,   0]], dtype=default_dtype),
                b = jnp.array( [1/6,  1/3,  1/3,  1/6], dtype=default_dtype),
                c = jnp.array( [0, 1/2, 1/2, 1], dtype=default_dtype),
                c_error = None,
                )
```

(Note the very last matrix element in the `a` field should be 0, not 1, if I am reading [the relevant Wikipedia page](https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta_methods) correctly.)

It should be a pretty easy thing to fix. :-)

**Comment by PhilipVinc** [comment]
Dammit! Thanks for the report. Btw @femtobit when you have time we should investigate why the test did not caught that…

The tableaus are copied from https://github.com/SciML/ODE.jl/blob/master/src/runge_kutta.jl and indeed there’s a typo.

Can you submit a PR fixing it? I’m on holiday for a while but can quickly merge it
Il 29 dic 2021, 13:26 +0100, Matematija ***@***.***>, ha scritto:

**Comment by Matematija** [comment]
Sure, I can do a PR. I'll give it a day to go over other coefficients, maybe there are other typos that sneaked by tests.

**Comment by femtobit** [comment]
Thanks for spotting the typo, @Matematija.

> Dammit! Thanks for the report. Btw @femtobit when you have time we should investigate why the test did not caught that…

The tests do not catch this typo because it does not actually affect the output of the solver. In RK tableaus, `a` is a lower triangular matrix we zero diagonal, because the slope `k[l]` only depends on `k[m]` where `m < l`. Otherwise, a slope would depend on itself (diagonal entries) or future slopes (upper diagonal entries).

In our RK step code, the slopes array `k` is zero-initialized, so by the time `k[l]` is computed, `k[m]` with `m >= l` is still zero and its coefficient does not affect the output. As a consequence, diagonal entries in the tableau can be arbitrary (though of course they should be zero for correctness).

I'll add a test to make some sanity checks to the tableaus.

**Comment by Matematija** [comment]
@femtobit - I see, it's just about symbolic correctness if all intermediate slopes are zero-initialized. Thanks for the explanation.

@PhilipVinc - I can still do a PR if you want me to but if nothing is actually broken, then it's not urgent.

I am okay with closing this now unless you want to keep this issue around as a reminder.

**Comment by PhilipVinc** [comment]
Ah that’s good that nothing is broken.
But I’d still fix it. It’s an error after all
Il 29 dic 2021, 21:18 +0100, Matematija ***@***.***>, ha scritto:

**Comment by femtobit** [comment]
> I see, it's just about symbolic correctness if all intermediate slopes are zero-initialized. Thanks for the explanation.

Indeed. Although your report made me realize that our test are not actually sensitive to errors in the lower triangle as well. This is because the ODE system in the fixed-step tests does not depend on `x` (only `t`) and therefore is completely independent of `tableau.a`.

I'll make a PR updating our tests to be sensitive to errors in `a`. Since it is easy to fix the typo underlying this issue to, while I'm already doing this, I think its not necessary for you, @Matematija, to prepare a separate PR just for that. But you are very welcome to report any other typo you may spot in the tableaus. While larger errors should be caught by the updated tests, small perturbations in the coefficients could lead to only slightly worse solutions, which is much harder to detect automatically.
