### ISSUE TITLE
TensorBoardLog with MPI

### ISSUE THREAD

**Issue by jwnys** [netket/netket#1078]
Not sure this can be solved in netket, but when using TensorBoardLog with MPI, I'm getting errors.

MWE (mpitest.py):
```python
import netket as nk
logger = nk.logging.TensorBoardLog("test_mpi_log")
```

When you run the above with
```console
mpirun -np 4 python ./mpitest.py
```

You'll see messages like:
```console
KeyError: 'test_mpi_log'

FileExistsError: [Errno 17] File exists: 'test_mpi_log'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/localjw/lib/python3.8/site-packages/tensorboardX/record_writer.py", line 47, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
```

**Comment by femtobit** [comment]
This also affects the other loggers right? There is a reason our default logger initialization looks like this:
https://github.com/netket/netket/blob/bdf7071ff4000a31adce360a86f132708fc6db82/netket/driver/abstract_variational_driver.py#L235-L243

**Comment by PhilipVinc** [comment]
No, because the other loggers (`StateLog` and `JsonLog`) are lazily initialised: they don't create the output files until they actually have to write them (see [this for example](https://github.com/netket/netket/blob/bdf7071ff4000a31adce360a86f132708fc6db82/netket/logging/state_log.py#L165)). And since our drivers don't log on `rank != 0`, this is not an issue.

Basically, as long as a logger is lazily initialised, there are no issues.

The choice was made so that loggers are not MPI-aware (that's why they should be lazy)
