### ISSUE TITLE
Diffrax

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#1109]
https://github.com/patrick-kidger/diffrax has been realeased, including support for SDEs. I think it might make sense to eventually drop our internal ODE solver in favor of this. What do you think @femtobit @PhilipVinc?

**Comment by femtobit** [comment]
I have seen this too and I agree this looks very promising. I haven't looked at it in depth, but it seems many of the design decisions align with what @PhilipVinc and I had in mind for future extensions of our solvers.

Using `diffrax` as a basis instead of our own solver code is definitely something to consider. We need to figure out how well it plays with some of the more exotic things we are able to do now (like the QGT-based norm which ideally requires information from an EOM evaluation).
