### ISSUE TITLE
Stochastic reconfiguration for RNN

### ISSUE THREAD

**Issue by danielalcalde** [netket/netket#1131]
The partition function of an RNN is always Z=1 and so a simpler version of the stochastic reconfiguration algorithm could be used:
![lagrida_latex_editor](https://user-images.githubusercontent.com/53435922/157089287-dedc99eb-590c-4856-a461-e6246457447a.png)

 Is this currently implemented?

**Comment by PhilipVinc** [comment]
No, but the current formula is correct nevertheless.

And the additional computational cost is negligible. Do you really need to get rid of this extra term?

**Comment by gcarleo** [comment]
No this is not implemented at the moment, it could be done by adding a flag that would ask not to subtract the product of means. However I believe that the version with subtracted means is intrinsically less noisy, even for the arnn

**Comment by danielalcalde** [comment]
Mhm, I thought that assuming Z=1 might be less noisy, but you might be right. The reason I wanted to try this is to deal with an initial wave function initialized in the spin-up state. There only one configuration is sampled and so F and S are zero. I would expect this pathological case should work better with the simpler S matrix. Could you direct me to the parts of the code where the S and F are calculated so that I can play around with it?

**Comment by PhilipVinc** [comment]
Yea it's very easy to change.
Should be a one liner.

I'll send you the links later

**Comment by PhilipVinc** [comment]
So, in NetKet there are 3 implementations of the Quantum Geometric Tensor (the S matrix). Depending on what you are doing, one might perform better than the other (if you want to read about it, check our paper there's a section on it).

The lines removing the average are:
 - For [`QGTOnTheFly`](https://github.com/netket/netket/blob/1d78986508142eea285c4566955f83fba7e557a1/netket/optimizer/qgt/qgt_onthefly_logic.py#L48) assuming you don't use chunking. Otherwise it's [a few lines below](https://github.com/netket/netket/blob/1d78986508142eea285c4566955f83fba7e557a1/netket/optimizer/qgt/qgt_onthefly_logic.py#L94)
https://github.com/netket/netket/blob/1d78986508142eea285c4566955f83fba7e557a1/netket/optimizer/qgt/qgt_onthefly_logic.py#L48
 - For [`QGTJacobianPyTree`](https://github.com/netket/netket/blob/1d78986508142eea285c4566955f83fba7e557a1/netket/optimizer/qgt/qgt_jacobian_pytree_logic.py#L108)  (to disable the centering just change it to `centered_jacobian_real_holo = tree_subtract_mean` and `centered_jacobian_cplx = jacobian_cplx`.) Those are actually used a few lines below in [here](https://github.com/netket/netket/blob/1d78986508142eea285c4566955f83fba7e557a1/netket/optimizer/qgt/qgt_jacobian_pytree_logic.py#L250) 
https://github.com/netket/netket/blob/1d78986508142eea285c4566955f83fba7e557a1/netket/optimizer/qgt/qgt_jacobian_pytree_logic.py#L108
 - For [`QGTJacobianDense`](https://github.com/netket/netket/blob/1d78986508142eea285c4566955f83fba7e557a1/netket/optimizer/qgt/qgt_jacobian_dense_logic.py#L290) just remove the call to `subtract_mean`. 
https://github.com/netket/netket/blob/1d78986508142eea285c4566955f83fba7e557a1/netket/optimizer/qgt/qgt_jacobian_dense_logic.py#L290

If you don't know what Implementation you're using, it means you're relying on an automatic heuristic that picks it for you. Please note that it depends on how many parameters you have so if you network gets large, it might switch... In that case I'd suggest you to fix it.
Anyway, to see what the automatic heuristic picks, just call `vstate.quantum_geometric_tensor()` and see what type is the resulting S matrix.

**Comment by danielalcalde** [comment]
thanks, will try it out and if I see any improvement for my use case I will put in a pull request

**Comment by PhilipVinc** [comment]
As for the gradient of the energy, it is [here](https://github.com/netket/netket/blob/1d78986508142eea285c4566955f83fba7e557a1/netket/vqs/mc/mc_state/expect_grad.py#L143)

https://github.com/netket/netket/blob/1d78986508142eea285c4566955f83fba7e557a1/netket/vqs/mc/mc_state/expect_grad.py#L143

again, assuming you are not using chunking. If you use chunking it is here

https://github.com/netket/netket/blob/1d78986508142eea285c4566955f83fba7e557a1/netket/vqs/mc/mc_state/expect_grad_chunked.py#L129

(it's a bit unfortunate a lot of code is duplicated with/without chunking... eventually we'll unify it, given some manpower)

**Comment by PhilipVinc** [comment]
By the way, if you happen to make a comparison, even a simple plot, I'd be curious to see it. I also think, like Giuseppe, that this formula should be more stable, but I've never checked it so having an actual confirmation would be nice.

--

A side note: I've long wanted to add a standard, simple RNN implementation to `netket.models`. Since you mentioned you're working with RNNs, we would be very happy if you wanted to contribute a generic implementation, a bit like the autoregressive networks we already have.

**Comment by danielalcalde** [comment]
I would be happy to contribute! For now, I only have a 1 layer 1D implementation, but if I manage to overcome the difficulties with the wave function having a lot of zeros at the beginning of the time evolution I plan to also implement the RNN for 2D.

**Comment by danielalcalde** [comment]
I can confirm @gcarleo statement that the version with subtracted means is intrinsically less noisy. Sadly the approach did also not solve my other problem.

**Comment by PhilipVinc** [comment]
What is your problem?

**Comment by danielalcalde** [comment]
If my initial state has many zeros I do not get any time evolution.
The simplest example is a 1 spin half wave function with \psi(1)=exp(-a), \psi(-1)=1-exp(-a) that I try to evolve with H=\sigma_x.
If a is large enough I will never sample the -1 state and so the F vector will be zero. The unsatisfying solution is to just choose a to be small enough so that you sample some -1 but big enough that your state is close to your desired starting state.

**Comment by PhilipVinc** [comment]
Yeah, this kind of states are very hard to treat with TDVP.

A trick is to change the computational basis to something more amenable (Y or X instead of Z).

Or supervise-learning of the dynamics.
