### ISSUE TITLE
Signal to noise Ratio regularization for tdvp

### ISSUE THREAD

**Issue by danielalcalde** [netket/netket#1140]
I have at the moment hacky implementation of the SNR regularization from https://arxiv.org/pdf/1912.08828.pdf, which for the system I'm studying leads to a more stable TDVP evolution. 

To compute the SNR you need to compute both the mean and variance of \rho_k(s)=(V^\dagger) _{k, k’} O_k’(s) O_loc(s). Where V are the eigenvectors of the quantum geometric tensor.
The SNR can then be computed with snr_k=sqrt(N_samples) * abs(\rho_mean_k)/\rho_std_k. 

The last step of the algorithm is to remove all \rho_k with an SNR smaller than a threshold (2 works quite well). \rho_mean_k is just a linear transformation of the F_k vector, but to compute the variance you need the O_k(s)*O_loc(s).

The main challenge to get this working cleanly in netket is to somehow pass O_k(s)*O_loc(s) to the solver. I suggest adding a new TDVP equation class that could then be easily be customized for this or other purposes.

The idea would be that instead of doing this:
```
E, F = variational_state.expect_and_grad(hamiltonian)
S = variational_state.quantum_geometric_tensor(qgt_T) + diag_shift
dw, _ = S.solve(solver, F)
```
we would be doing something like this:
```
tdvp_eq = variational_state.tdvp_equation(qgt_T)
dw, _ = tdvp_eq.solve(solver, diag_shift=diag_shift)
```

I'm open to suggestions.

**Comment by femtobit** [comment]
Yes, that's a great idea. I was planning to do the same thing and what you are suggesting makes a lot of sense. If you already have a "battle-tested" JAX-based implementation, you are of course welcome to contribute it.

I would like to remove the `linear_solver` argument of the `TDVP` in favor of this. We can rename it to `tdvp_solver` (and the additional `linear_solver_restart` argument can be part of the `tdvp_solver` object too, which is much better.)

I made a quick prototype implementation for this once, I've just put commited it in and pushed it to a [branch `tdvp_solver`](https://github.com/netket/netket/tree/tdvp-solver) here, feel free to take a look and compare to what you have in mind. Writing a variant of the `DefaultTDVPSolver` class there to solve this using the signal-to-noise regularization should be possible (the relevant quantities are accessible through the driver).

**Comment by femtobit** [comment]
Okay, I think I need to add that there is the additional difficulty of getting access to the local energies within the TDVP solver. The `O_k`s are easier, because IIRC `QGTJacobianDenseT` contains them as `.O` member.

The local energies are computed deep within the grad/expect logic, I think specifically [`grad_expect_hermitian`](https://github.com/netket/netket/blob/216092e501fa6ba7b73a4caa1fef68af4df452ea/netket/vqs/mc/mc_state/expect_grad.py#L118). They are not returned though, only their summary statistics.

I think it would be great if we could an option to get the local estimators from `MCState.expect_and_grad`, then we could use them in the TDVP solver without having to duplicate (possibly large) parts of the grad/expect logic. @PhilipVinc What do you think, is this viable (the local values as optional return would need to be propagated through all the dispatches)? Or do you see a better way?

**Comment by PhilipVinc** [comment]
This has been implemented for a while now...
