### ISSUE TITLE
Wave function log

### ISSUE THREAD

**Issue by NnktYoshioka** [netket/netket#120]
Hi, 

Attempting to look at the iteration of wavefunction,  I noticed `.wf` is overwritten every `SaveEvery` steps.
From #66 I assume there is a technical problem concerning the stability of MPI. 
Is there any easy way to get around, e.g. outputting into different files?

**Comment by gcarleo** [comment]
Hi @NnktYoshioka , the expected behavior is that the wave-function is overwritten every  `SaveEvery`. There is not instability with MPI, the idea is that only the last wave-functions are saved during the optimization. If you need to save the wave-function at all steps, this will be particularly easy with version 2.0, to be released some time later this year. You can already try it on the branch v2.0, but that might be unstable.
