### ISSUE TITLE
Problems with new version 3.5.0

### ISSUE THREAD

**Issue by RomanArmenta** [netket/netket#1302]
Hello. I'm having problems using the newest version of Netket when I want to use it to optimize the Bose-Hubbard model through an RBM model. I get this error and I don't know how to solve it, and I don't know how to do a roll-back to netket 3.4.2. Can you help me, please? 

Here is the notebook:
https://www.dropbox.com/s/dqo7kmyonr286qk/Bose-Hubbard%28hot%20encoding%20example%29.ipynb?dl=0

Thanks.

`
AttributeError: module 'jax' has no attribute 'tree_multimap'
`

**Comment by PhilipVinc** [comment]
I don't think this is NetKet problem. In fact the last netket release fixes this issue.

If you read the warning it tells
```python
      "/home/romanar/.local/lib/python3.9/site-packages/optax/_src/update.py:42: FutureWarning: jax.tree_multimap is deprecated, and will be removed in a future release. Use jax.tree_map instead.\n",
```

The actual reason is that you have a too recent jax version but a too old flax or optax version.
In recent jax versions they removed `jax.tree_multimap` and you should use `jax.tree_map` instead.
You should run
```
pip install --upgrade netket jax optax flax chex
``` 

And if you have in that notebook some appearances of `tree_multimap`, replace them with `tree_map`
