### ISSUE TITLE
Memory-allocation overhead when using LocalOperators for hilbert.Fock

### ISSUE THREAD

**Issue by Z-Denis** [netket/netket#1555]
As identified in #1554, constructing hopping operators using the LocalOperator allocates a lot. Here is an example:

```python
import jax.numpy as jnp
from netket.hilbert import Fock
from netket.operator.boson import create, destroy

n_sites = 36
hi = Fock(n_particles=n_sites, N=n_sites)
op = sum([create(hi, i) * destroy(hi, j) for i in range(n_sites) for j in range(n_sites)])
conf = jnp.ones(n_sites)

sol = op.get_conn(conf)
```

The execution of the last line involves allocating 27.9GiB, upon its first call only. Maybe some heavy numpy static calculations?

**Comment by PhilipVinc** [comment]
I think that’s because we are building the 37^2 dense matrix and doing stuff on it…Try editing netket/operator/boson.py to feed sparse matrices instead of dense to the local operator. Does that help?On 3 Aug 2023, at 13:41, Zakari Denis ***@***.***> wrote:﻿
As identified in #1554, constructing hopping operators using the LocalOperator allocates a lot. Here is an example:
import jax.numpy as jnp
from netket.hilbert import Fock
from netket.operator.boson import create, destroy

n_sites = 36
hi = Fock(n_particles=n_sites, N=n_sites)
op = sum([create(hi, i) * destroy(hi, j) for i in range(n_sites) for j in range(n_sites)])
conf = jnp.ones(n_sites)

sol = op.get_conn(conf)
The execution of the last line involves allocating 27.9GiB, upon its first call only. Maybe some heavy numpy static calculations?
