### ISSUE TITLE
OpenMPI MPI_Init error occurs when importing NetKet

### ISSUE THREAD

**Issue by AndyMc629** [netket/netket#182]
Have installed netket and have all the required prerequisites already installed on my Ubuntu 16.04 LTS OS.

Have opened up a Jupyter notebook and ran the following command to check installation

```python
# Import netket library
import netket as nk
```

and the kernel dies and I get the following stderr output in my terminal:

```bash
[andrew-ThinkStation-P300:02140] mca: base: component_find: unable to open /usr/lib/openmpi/lib/openmpi/mca_shmem_sysv: /usr/lib/openmpi/lib/openmpi/mca_shmem_sysv.so: undefined symbol: opal_show_help (ignored)
[andrew-ThinkStation-P300:02140] mca: base: component_find: unable to open /usr/lib/openmpi/lib/openmpi/mca_shmem_posix: /usr/lib/openmpi/lib/openmpi/mca_shmem_posix.so: undefined symbol: opal_shmem_base_framework (ignored)
[andrew-ThinkStation-P300:02140] mca: base: component_find: unable to open /usr/lib/openmpi/lib/openmpi/mca_shmem_mmap: /usr/lib/openmpi/lib/openmpi/mca_shmem_mmap.so: undefined symbol: opal_show_help (ignored)
--------------------------------------------------------------------------
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_shmem_base_select failed
  --> Returned value -1 instead of OPAL_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_init failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[andrew-ThinkStation-P300:2140] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[I 16:28:49.165 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel c58795c7-4474-45a7-8fe8-c444fc16b2fe restarted
[I 16:30:40.190 NotebookApp] Saving file at /netket-playground/tutorials-and-examples/Heisenberg1d.ipynb
```

Has anyone else been having this issue? I've reinstalled my OpenMPI installation from source and I can compile and run mpicc examples.

Would appreciate some advice on even where I should be looking in the source code for the fault, it's been very hard to diagnose (most online examples of this issue just suggest recompiling your OpenMPI installation)

Thanks in advance!

**Comment by gcarleo** [comment]
Please run CC=mpicc CXX=mpicxx pip install netket , this should solve the issue

**Comment by AndyMc629** [comment]
Hi, uninstalled netket then ran the command you suggested, still same error I'm afraid.

**Comment by gcarleo** [comment]
Then it's an environment problem... Use a clean envinroment to install everything https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment

**Comment by AndyMc629** [comment]
Hi, just tried in a clean python environment - still same error. Must be a wider environment issue with my MPI installation (rather than my python env). I'll keep digging.

**Comment by gcarleo** [comment]
Sorry these didn't work. It must be something more specific to your mpi installation then. Maybe @femtobit can tell you more for Ubuntu

**Comment by gcarleo** [comment]
Have you tried running it outside of a jupyter notebook though?

**Comment by AndyMc629** [comment]
Yeah just tried in the python terminal same thing. Yeah I think it must be the mpi installation. Tried making sure that was clean by reinstalling but has to be at that end. Thanks anyway, I'll let you know if I find fix in case anyone else comes up against it!

**Comment by femtobit** [comment]
> Sorry these didn't work. It must be something more specific to your mpi installation then. Maybe @femtobit can tell you more for Ubuntu

I remember this issue, I think it is the same I had since PR #109. I can still reproduce it on Ubuntu 18.04 with OpenMPI (though this does not occur when using MPICH).

@AndyMc629 Could you try installing the `mpi4py` package and then running:
```python
from mpi4py import MPI
import netket as nk
```
I would be interested whether this fixes the problem for you (it does on my system). If so, I believe this indicates there is still a problem with our MPI initialization as implemented in PR #109.

**Comment by gcarleo** [comment]
@AndyMc629 did this solve your issue? I also can confirm that doing what suggested by @femtobit solves this problem on some linux workstations. We will need to understand why this happens, but this is a good workaround for the moment.

**Comment by chojunghee** [comment]
I have the same issue and the method @femtobit suggested also does not work :(

**Comment by twesterhout** [comment]
* If `python -c "from mpi4py import MPI"` doesn't work, then it's a problem with your setup;
* If `python -c "from mpi4py import MPI"` works, but `python -c "from mpi4py import MPI; import netket"` fails, then it's most probably a problem with your setup (e.g. `mpi4py` and `netket` were compiled against different MPI installations);
* If `python -c "from mpi4py import MPI; import netket"` works, but `python -c "import netket"` fails, then it's a bug in `netket`.

If it turns out to be a bug in `netket`, I'm willing to work on fixing it, but no sooner than next week I'm afraid. I also have an idea where the problem could lie, but since I can't reproduce it locally, I'm going to need a volunteer who's willing to run tests and supply me with information :)

**Comment by chojunghee** [comment]
I'm on the second case. Well how can i check compile dependencies?

**Comment by twesterhout** [comment]
> I'm on the second case. Well how can i check compile dependencies?

@chojunghee you could try running `ldd` on `netket` and `MPI` python extensions (read shared libraries). If they point to different `libmpi`'s then you can try recompiling at least one of the two.

**Comment by gcarleo** [comment]
In any case, I feel we need to write a troubleshooting guide for this kind of issue, since it happens a lot of times... It's really unfortunate that we can't do much better than this though, because in any case these issues are system related. The thing that I find a bit strange is our need for the `mpi4py` initialization in some cases... @twesterhout maybe we should look into this, yeah
