### ISSUE TITLE
SR defaults overwriting QGT properties

### ISSUE THREAD

**Issue by jwnys** [netket/netket#1861]
First of all: apologies if I'm missing something here.

I'm wondering about the following behavior: I want to run SR with diag_shift=1e-6 and diag_scale=1e-4 (just to have some values in mind). Here are two lines of code that I've used interchangably:
```python
qgt = nk.optimizer.qgt.QGTJacobianPyTree(holomorphic=True, diag_shift=1e-6, diag_scale=1e-4)
sr = nk.optimizer.SR(qgt=qgt)
```
and
```python
qgt = nk.optimizer.qgt.QGTJacobianPyTree
sr = nk.optimizer.SR(qgt=qgt, holomorphic=True, diag_shift=1e-6, diag_scale=1e-4)
```
The reason for doing the first is that this is the way you would need to run dynamics (see e.g. https://github.com/netket/netket/blob/2752e7928570aa3e180e2e3f0f387c0b1764c43b/Examples/Dynamics/ising1d.py#L65)
While the second is something that is maybe closer to the examples on doing VMC.

Now, it's my understanding that the first one actually quietly overwrites the diag_shift and diag_scale with its default values (0.01 and None). Is this intended behavior?

PS: It sounds a bit strange to me also that e.g. holomorphic is taken from the qgt object, but the regularization properties are overwritten?

**Comment by PhilipVinc** [comment]
Nice find...

It happens because inside of SR, where we construct the QGT
https://github.com/netket/netket/blob/2752e7928570aa3e180e2e3f0f387c0b1764c43b/netket/optimizer/sr.py#L148

we explicitly specify `diag_shift` and `diag_scale` while we pass all other extra arguments as a dict.
This means that the shift and scale arguments of 
```
qgt = nk.optimizer.qgt.QGTJacobianPyTree(holomorphic=True, diag_shift=1e-6, diag_scale=1e-4)
```
are always ignored. Any other argument that is re-specified on the SR object would also be overridden.


This all happens silently because `functools.partial` does not warn if you specify twice the same keyword argument
```python
def f(x,y): x*y
g = partial(f, y=3)
g(1, y=10) # works
```

--

I'm not sure what the best strategy would be here. One thing that we could do is to make this error, by validating inside of SR that the arguments that we are specifying were not specified already.

What else, I'm not sure..

**Comment by jwnys** [comment]
I think for now it would be useful to at least throw some warnings just so we are aware of it when it happens.

**Comment by PhilipVinc** [comment]
What precise case/condition would you suggest should warn?

**Comment by jwnys** [comment]
The case where the QGT already has some diag_shift/diag_scale specified, so the first case.

**Comment by Daniel-Haas-B** [comment]
Hi all,

First, is this still relevant? Trying to tackle this just to get more involved with the project.
Also, would the ideal solution then only warn if there is a silent overwrite? For example, am I correct to assume the following test case?

```python
  # Test case 4: QGT with values, SR specifies different values (no warnings)
  qgt_instance = qgt(vstate, diag_shift=1e-3, diag_scale=1e-5)
  with warnings.catch_warnings():
      warnings.simplefilter("error")
      sr = nk.optimizer.SR(qgt=qgt_instance, diag_shift=1e-4, diag_scale=1e-6)
```

The fact that QGT does not have `diag_scale` and `diag_shift` as attributes is making my solution a bit convoluted...

**Comment by PhilipVinc** [comment]
SR does not take a QGT instance, but rather a function to construct the QGT. That's because SR is an algorithm.
So the way you build SR is rather `SR(qgt=nk.optimizer.qgt.QGTJacboainDense(diag_shift=1e-5)
, diag_shift=1e-5)`.

So you can check for this kind of usage and raise an error in that case. The test case could then be
```python
  # Test case 4: QGT with values, SR specifies different values (no warnings)
  qgt_constructor = qgt(diag_shift=1e-3, diag_scale=1e-5)
  with pytest.raises(Exception):
      sr = nk.optimizer.SR(qgt= qgt_constructor, diag_shift=1e-4, diag_scale=1e-6)
```

(we use [pytest, so in the test files you should use `pytest.raises`](https://docs.pytest.org/en/7.1.x/how-to/assert.html#assertions-about-expected-exceptions) )

You can safely assume that `qgt_constructor` is either a function when the user does `qgt_constructor=nk.optimizer.QGTJacobianDense` (in which case no diag shift was specified) or a `partial` if the user does `qgt_constructor=nk.optimizer.QGTJacobianDense(diag_shift=3)`.

You can check `ifinstance(qgt_constructor, partial)` and look into the declared keyword arguments, and error if needed.

**Comment by PhilipVinc** [comment]
Actually the case that should fail are of the form:
```python
sr = nk.optimizer.SR(qgt= qgt(diag_shift=1e-3))
sr = nk.optimizer.SR(qgt=qgt(diag_scale=1e-3))
```
because SR always overwrites diag shift and scale. this is easy to check as discussed above (check if it is a partial + the keyword argument is in there)

Then, you can also look at another overwriting
```python
sr = nk.optimizer.SR(qgt= qgt(some_thing=1), some_thing=2)
```
but that is less common, and less urgent. Though it can also be done in a similar fashion.
