### ISSUE TITLE
OpenMP requirement is problematic on Mac 

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#225]
I get error messages such as Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) etc, but I have OpenMP installed with brew... 

It might be related to this issue https://github.com/fospald/fibergen/issues/5 , I suggest to either try to implement this fix or remove the use of OpenMP by default ON

**Comment by twesterhout** [comment]
@gcarleo yes, that's a known issue and is the reason why OpenMP is disabled for `xcode10.2` on Travis CI. I'm very strongly against disabling OpenMP by default, since it's not our code that's causing problems. It's a shame to significantly slow down the code just because some environments are not set up properly.

If after installing OpenMP you can compile a simple program like this
```c
#include <omp.h>
#include <stdio.h>

int main() {
  int i, thread_id, total_threads;
#pragma omp parallel default(none) private(i, thread_id, total_threads)
  {
    total_threads = omp_get_num_threads();
    thread_id = omp_get_thread_num();
#pragma omp critical
    fprintf(stdout, "Hello from %i out of %i!\n", thread_id, total_threads);
  }
  return 0;
}
```
then there's hope and we can try to come up with a workaround for it in CMake. I don't have a Mac to test stuff on, so I'm afraid you're on your own here.

**Comment by PhilipVinc** [comment]
We could check if OpenMP is found on Mac, and if not, simply disable USE_OPENMP, for now.

```
if(NETKET_USE_OPENMP AND APPLE)
    find_package(OpenMP)
    if(NOT OpenMP_FOUND)
      set(NETKET_USE_OPENMP OFF)
    endif
end
```

**Comment by PhilipVinc** [comment]
We could even go further and 'guess', on failure, that `openMP` was installed via brew but I need to experiment a bit.

**Comment by gcarleo** [comment]
The problem is that if you want to run pytorch on a mac, you need to install libomp with brew. However this doesn't seem compatible with our installation... that's why I am little bit against putting this as a default ON option if we don't have control over these issues

**Comment by PhilipVinc** [comment]
@gcarleo no. I believe this to be just a problem with CMake on mac. As suggested [here](https://stackoverflow.com/questions/46414660/macos-cmake-and-openmp) if you pass it explicitly the paths, he correctly compiles.

**Comment by gcarleo** [comment]
OK, I have put the patch you suggested. For the moment that's good enough to prevent a lot of failed installs ... #226
