### ISSUE TITLE
Updating RBM parameters in Stochastic Reconfiguration

### ISSUE THREAD

**Issue by sindhura97** [netket/netket#275]
I have a question about how you perform parameter updates using stochastic reconfiguration for RbmSpinPhase Machine.

Here, S and F can be complex valued. So, deltap can be complex valued. However, I see that you are setting the imaginary parts of deltap to 0. How can this be justified?

**Comment by gcarleo** [comment]
RbmSpinPhase is non holomorphic, thus we use the SR update for non holomorphic functions. In the case of RbmSpinPhase you can see that all weights and biases are real valued, thus the output of the network is a complex function of real parameters. Also notice that in the SR update we take the real part of S and F, and then solve for deltap. Thus deltap is by definition real, as it should be, since the parameters are purely real.  

For the holomorphic case, the wave function is a complex function of complex parameters, and it is differentiable with respect to these complex parameters. In that case, the SR update does not take the real part of S and F, and deltap is complex valued, as it should be. 

All of these rules can be derived by carefully deriving the analytical expressions for the SR updates in the two cases.

**Comment by sindhura97** [comment]
Thank you for the clarification. Is there any literature you could point me to that shows that "It is valid to solve S.real * deltap = F.real when deltap is restricted to be real " ?

**Comment by gcarleo** [comment]
This should be written in the [book](https://www.cambridge.org/core/books/quantum-monte-carlo-approaches-for-correlated-systems/EB88C86BD9553A0738BDAE400D0B2900) of Becca and Sorella, chapter 6
