### ISSUE TITLE
How to sample all Hilbert Space?

### ISSUE THREAD

**Issue by VolodyaCO** [netket/netket#333]
I want to use netket to force the variational Monte Carlo method to compute averages exactly (i.e. "sampling" the whole Hilbert space) for a small Hilbert space, only for benchmarking purposes. How can I do this? I tried using the ExactSampler sampler, but I am not sure how to configure the variational Vmc class to force the sampler to use all the states of the Hilbert space. Thanks. (Also, I don't know how to tag this as a question)

**Comment by gcarleo** [comment]
It is not possible at the moment to compute non-stochastic expectation values within the VMC loop... This would be maybe interesting for debugging, however ExactSampler is a better test there, since it really mimicks what happens on the large system (i.e. you don't sum over all hilbert space , but you sample over states sampled according to |psi(x)|^2)
