### ISSUE TITLE
Time-evolution: new design

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#435]
Now that everything is pythonically [~ugly~](https://www.youtube.com/watch?v=BCQpitbo-SA) nice, writing a variational time integrator that plugs into scipy is quite easy. I would like to take the occasion to unify the interface among time evolution and standard drivers, so this is an issue to discuss this.

Requirements:
- The interface should be consistent with the vmc optimization drivers as much as possible
- The interface should support open and hamiltonian evolution, otherwise [people](https://github.com/netket/netket/graphs/contributors) will break my beloved lindblad without me noticing 
- Should reuse other package's time-integrators. I [am lazy](https://en.wikipedia.org/wiki/Sleep) and don't like to for the millionth time a RK integrator
- Should be somewhat easy to plug another package integrator in, if needed.

Wishes:
 - I like the idea of it being easy to first define a problem (machine, initial state, time interval) and then solve it repeatedly with different solvers/timesteps/options. For anyone, this is essentially the [DiffEq/SciML interface](https://docs.sciml.ai/dev/tutorials/ode_example/), where you first define a problem and then you solve it. I don't know if this is feasible but that would be nice.
```julia
f(u,p,t) = 1.01*u
u0 = 1/2
tspan = (0.0,1.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob, rk45(), reltol=1e-8, abstol=1e-8, dt=0.001)
``` 

Conceptually, this means:
 - Define as usual the machine, the sampler
 - You *MUST* define the SR object at some point, because it is always required
 - Define the (potentially time dependent) hamiltonian/lindblad you wish to integrate.
 - Define the integrator, and all it's related options (in order to be generic, those arguments should be forwarded...)
- Define the interval in time we wish to integrate upon.

possible implementation:
in order to be somewhat portable, we need to be able to output a lambda function that takes a flattened vector of parameters and computes the gradient, which is equivalent to defining the function that defines an ode:
```python
def create_odefun(op, sampler, *args, **kwargs):
    machine = sampler._machine
    if not isinstance(machine, AbstractDensityMatrix):
        driver = Vmc(op, sampler, *args, optimizer=None, **kwargs)
    else:
        driver = SteadyState(op, sampler, *args, optimizer=None, **kwargs)

    def _fun(t, w):
        machine.parameters = unflatten(w)
        dp = driver._time_evo_step()
        return flatten(dp)

   return _fun, driver
```

It would be a worthwhile discussion whever this `time_evo_step` method should live in `vmc.py` and `steadystate.py` or it should be a separate class, or just a standalone method that does dispatch.

Having this function I can already plug into scipy, diffeqpy or any other integrator module easily.
Everything else is fancy logging and parameter handling. My main preoccupation for this is that we want to compute observables only ever once in a while (otherwise it really gets slow fast). And unfortunately scion does not allow callback hooks like that.

--

Since we like to be fancy, we would like to have an higher level `TimeEvolution` driver.
An initial proposal might be something along the lines of the following. 
```python
H = ...
ma = nk.machine.rbmspin(hilbert=hi, alpha=1)
ma.parameters = my_physical_state
sa = nk.sampler.MetropolisLocal(machine=ma, n_chains=8)
sr = nk.optimizer.SR(diag_shift=0.001, use_iterative=True, sparse_tol=1e-6, sparse_maxiter=1000)

tevo = TimeEvolution(H, sa, sr=sr, n_samples=2000) # incase of a density matrix also, sampler_obs=sa_obs, n_samples_obs=500)
tevo.solver("rk45", t_0=(1.0, 2.0), dt=0.01, adaptive=False)

tevo.run(1.0, out="test", obs=obs, step_size=0.02) # goes from 1.0 to 2.0, saving logs every 0.02
 48%|██▎      | 0.4800/1.0 [05:28<18:19, 723.68s/time, Energy=-25.3 ± 0.01 [var=4.6e+01, R_hat=0.9993]] 
pars_end = copy(ma.parameters)


# now if I want to test out a different tilmestep I should do...
ma.parameters = my_physical_state
tevo.solver("rk45", t_0=1.0, dt=0.005, adaptive=False)
tevo.run(1.0, out="test", obs=obs, step_size=0.02) # goes from 1.0 to 2.0, saving logs every 0.02
...

# that's better! now I continue my integration to t=3.0
tevo.run(1.0, out="test", obs=obs, step_size=0.02) # goes from 2.0 to 3.0, saving logs every 0.02
...
```

I already implemented the above, and it's nice that it uses the same `run` interface of Abstractdriver with only minimal changes. Ill admit this is not the best interface ever. But it allows to have a nice driver interface while also being able to call `iterate` manually for only a few iterations if one so whishes.

One thing I don't like is that if you randomly interrupt this, you will have random parameters for a random Time stored in the machine you have referenced outside... but this is a core design of netket, so I'm not sure we can do much about it.

Alternatively we might more go for something like
```python
H = ...
ma = nk.machine.rbmspin(hilbert=hi, alpha=1)
ma.parameters = my_physical_state
sa = nk.sampler.MetropolisLocal(machine=ma, n_chains=8)
sr = nk.optimizer.SR(diag_shift=0.001, use_iterative=True, sparse_tol=1e-6, sparse_maxiter=1000)

tevo_prob = TimeEvolutionProblem(H, sa, time_interval, sr=sr, n_samples=2000)
final_state, logged_obs = solve(tevo_prob, "rk45", dt=0.01, adaptive=False, obs=obs)

# want to try out other dt
final_state_dt2, logged_obs_dt2 = solve(tevo_prob, "rk45", dt=0.005, adaptive=False, obs=obs)

# that's better! now let's continue the time evolution...
tevo_prob_2 = TimeEvolutionProblem(H, sa, time_interval_2, sr=sr, n_samples=2000, state= final_state_dt2)
# state= will simply assign to the machine..
final_state_3, logged_obs_3 = solve(tevo_prob_2, "rk45", dt=0.005, adaptive=False, obs=obs)
```

I like this because it splits conceptually the time integrator (the solver) from the definition of the problem itself. However the first one is simpler to use in general if you don't play around much with solving the same thing with different solvers, but only integrate once.

In my experience when working with time evolution one does many tests at first, but then settles for one thing....
So i dunno.
What do you think?

Miscellaneous stuff:
- SciPy does not support fixed time-step integration! 
   - kinda. But I've been playing around recently with it, and if you set `abstol, reltol= ∞` and `max_dt`, effectively you are fixing the dt to that value. It works well.
- I don't like your jokes
   - Meh. me neither.

**Comment by PhilipVinc** [comment]
cc @femtobit @twesterhout and whoever wants to chip in

**Comment by gcarleo** [comment]
Oh I love your jokes.  

Anyways, 

```python
H = ...
ma = nk.machine.RbmSpin(hilbert=hi, alpha=1)
ma.parameters = my_physical_state
sa = nk.sampler.MetropolisLocal(machine=ma, n_chains=8)

rk=nk.ode.rk4(dt=0.01,adaptive=False)

tevo = TimeEvolution(H, sa, n_samples=2000, solver=rk, diag_shift=0.01)

tevo.run(tspan=(0.0, 2.0), out="test", obs=obs)
```

seems reasonable to me! It is ugly that one has to pass the "sr" arguments (diag_shift etc) by hand to the driver, and maybe we could think of an alternative. 

However I think that passing the SR object expicitly can be even more confusing? The SR solver can be used internally, but conceptually there is no way to use other "optimizers" in this case!

**Comment by gcarleo** [comment]
Also, at some point it would be nice if we could unify things in a way that we can define a "variational state" object for which we define <O> for some operator O, derivatives \partial <O> \partial p_k , and whatever else we need to minimize energy, do time evolutions and other main variational algorithms. 

In this way we could pass to the time evolution (or any other driver) just the "variational state" object, instead of the sampler, n_samples etc, that are just details of how you compute these expectation values. @femtobit did some experiments in this direction, but I think that we are still missing a unified way of looking at SR/t-vmc (say) using only these derivatives. 

Another slight advantage of this formulation is that one can immediately use these drivers for other classically tractable states (cluster mean field, MPS etc) that might compute these expectation values differently, without sampling.

**Comment by PhilipVinc** [comment]
My problem with 
```python
rk=nk.ode.rk4(dt=0.01,adaptive=False)
tevo = TimeEvolution(H, sa, n_samples=2000, solver=rk, diag_shift=0.01)
```
Is that technically you cannot instantiate a scipy solver without first having defined the `problem/function` you wish to integrate.
I would eventually like to simply forward all those arguments to scipy, without really checking them myself (so that if they ever update their api, as long as the first argument is the function, we are not going to break, and we will support new features mostly out of the box).

This is simple to implement if we create the solver *after* the problem/function.
This is a bit trickier to do before. What would we do? store all `**kwargs` in a structure, then forward them and really instantiate the scipy solver when constructing the Driver? Then it's confusing to see an error popping up because you passed a wrong kwarg to the solver, when from the user point of view he already created the solver object!

**Comment by PhilipVinc** [comment]
>  it would be nice if we could unify things in a way that we can define a "variational state" object

I don't want to sidetrack the discussion, but what would really go into a state? Is it a general formulation of the problem or really the derivatives at every iteration?

Because if it's the former, my proposal of Problem/Solver splitting is exactly a step in this direction, if we move SR from the problem to the state.
```python
tevo_prob = TimeEvolutionProblem(H, sa, time_interval, n_samples=2000)
final_state, logged_obs = solve(tevo_prob, "rk45",  sr=sr, dt=0.01, adaptive=False, obs=obs)
```
just rename Problem to state, and think that it will be the object holding all state information, simply decoupled from the solver itself.

**Comment by femtobit** [comment]
@PhilipVinc Thanks for bringing this up, especially with the nice illustrations of you design suggestions. In general, I like the problem/solver-type of splitting, at least in the way I've seen it in DifferentialEquations.jl.

I'll have to think more about this, but here are some preliminary points that come to my mind reading this discussion:

1. Specifying the problem and then solvers based on that does seem to have it's benefits (and there is probably a reason other libraries are going in that direction). In a way it's the inverse of the driver-type interface we have now, where you specify the solvers first and then pass them to a driver.
Notice how with the current design we have to take care to configure SR, optimizers, etc. with machine arguments (or, e.g., the time stepper with the number of parameters or the Hilbert space size depending on the application) and if we make a mistake there, that might lead to incorrect behavior (or in the better case an error message from the driver). That information, however, is all part of the problem definition and it's not like we're reusing the solvers for different problems (the would be no need, one can just create new ones). So setting up the solvers based on the problem definition in the way @PhilipVinc outlined it seems to be easier to use to me.

> However I think that passing the SR object expicitly can be even more confusing? The SR solver can be used internally, but conceptually there is no way to use other "optimizers" in this case!

2. I don't see why we can't just pass the SR object like for the drivers. SR is conceptually different from the other optimizers anyways and having to pass through parameters like lsq_solver or regularization methods like we did in NetKet v1 is just cumbersome and makes it harder to extend the SR. (The name SR does not fit perfectly, since to my understanding SR is usually the term used in the context of ground state calculations, but then again, in supervised learning it'd probably more natural to call it natural gradient, but we call it SR there as well. So I'd say let's just stick to that term.)

**Comment by PhilipVinc** [comment]
> In a way it's the inverse of the driver-type interface we have now, where you specify the solvers first and then pass them to a driver.

i am aware of that. But our driver-based schema seems to have some issues when working with time-evolution, which has a somewhat different interface from standard optimiser-like drivers.  I am not sure that the problem/solver interface is the best for our problem, but I think it's a very clear interface that it's worth keeping in mind in our discussion.
