### ISSUE TITLE
Can I use a Jax machine with a numpy sampler?

### ISSUE THREAD

**Issue by VolodyaCO** [netket/netket#491]
I wrote a custom numpy sampler that I am currently using with RbmSpin and RbmMultiVal machines. However, I'd like to try some jax machines as well. It seems that netket overrides the numpy samplers with jax samplers (I guess this is due to compatibility). The first question is if I can use numpy samplers with jax machines.

If this is not possible, after I write a custom Jax kernel class (such as `_JaxLocalKernel`), how do I use it? Would it be something like `nk.sampler.jax.JaxMetropolisHastings(my_custom_jax_machine, my_custom_jax_kernel)`?

**Comment by PhilipVinc** [comment]
Yes, numpy and jax samplers have somewhat different implementations in order to be high-performance.
Assuming you are using a metropolis-hastings sampler, and you only wrote a custom kernel for that, you can write a jax kernel yourself.

I recently gave a short crash course on how to do so. The associated python notebook is available to download [here](https://github.com/PhilipVinc/vmc-crash-course-2010/tree/master/1-intro-netket).
Note that it assumes you have the most recent v3.0 branch installed, BTW)

**Comment by VolodyaCO** [comment]
Yes, thanks. So I just need to "translate" the numpy kernel to the jax kernel in order to use the jax machine. I will try it to close this issue

**Comment by PhilipVinc** [comment]
BTW, @gcarleo just pointed out to me that you can probably still use the numpy kernel yourself, but you have to bypass our autodetection of a jax machine that forwards everything to the Jax MetropolisHastings sampler.

Essentially NumpyMetropolisHastings + NumpyKernel should still work with a jax machine, though performance will be terrible because the state vector will keep being copied at every sample step...

**Comment by VolodyaCO** [comment]
I guess I prefer to write it in jax then

**Comment by VolodyaCO** [comment]
@PhilipVinc I have been finding some difficulty. I am working with bosons, and I wanted to roll the states so that the leading site in the state is always the least occupied. I came to learn that I had to do this using `jax.lax` in the `transition` method of the Jax Kernel class:
```python
idx = jax.lax.argmin(state, axis=0, index_dtype=_np.int32)
sorted_state = jax.numpy.roll(state, idx)
```
Now, in the random state generation, I want to generate a state where every occupation is different. In numpy I did it like this:

```python
def random_state(self, state):
    for i in range(state.shape[0]):
        newstate =  -2 * _np.eye(self.num_sites) + 1
        idx = _np.arange(self.num_sites)
        _np.random.shuffle(idx)
        state[i] = newstate[idx].flatten()
```

where `self.num_sites` is the number of sites. I tried to translate this to jax:

```python
def random_state(self, key, state):
    keys = jax.random.split(key, 2)
    newstate = -2 * jax.numpy.eye(self.num_sites) + 1
    idx = jax.numpy.arange(self.num_sites)
    idx = jax.random.permutation(keys[1], idx)
    state = newstate[idx].flatten()
return keys[0], state
```

Now, this does produce one state, but not a batch. Do you know how can I create this batch? I mean, `random_state` produces a state of the form `Traced<ShapedArray(int64[15])>with<DynamicJaxprTrace(level=1/1)>` (`self.num_sites=15`), but it should produce a state of the form

```shell
Traced<ShapedArray(int64[15])>with<BatchTrace(level=3/2)>
  with val = Traced<ShapedArray(int64[4,15])>with<DynamicJaxprTrace(level=2/2)>
       batch_dim = 0
```
where there are 4 chains.

Thanks!

**Comment by PhilipVinc** [comment]
with #539 this will be easy to do and well supported
