### ISSUE TITLE
Parallel tempering samplers in Jax

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#494]
As of now, parallel tempering samplers are not implemented in Jax but only in numpy.

**Comment by PhilipVinc** [comment]
With #539 parallel tempering samplers are now implemented in Jax, however, they don't reliably pass tests.
I suspect they are actually correctly implemented, but the tests are failing because of precision issues, but we should investigate better and get the tests or the implementation up to shape.

Because of this, we _disabled_ them from the release.

In order to use the PT samplers you must set the environment variable `NETKET_EXPERIMENTAL=1` or run `netket.config.update(`NETKET_EXPERIMENTAL`, True)` in python.

Help still wanted
