### ISSUE TITLE
Travis switching to Paying for MacOs CI

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#495]
Travis recently announced that starting 2 november 2020 that they will start to charge for CI testing on MacOS after an initial free credit of 500 MacOs build minutes.

They also say that nothing will be changing for linux builds, but then they say that they also will be asking Open Source Software to apply to get free credits for Linux builds. By default they will grant 1000 minutes to OSS... It's unclear to me

[Here is the announcement](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).
The changes maybe won't affect us immediately because they will be 'slowly migrating repositories to the new plan model'.

@gcarleo 500 MacOs build minutes will disappear somewhat quickly, considering that the fast macos build takes 20 minutes and the slow 40.... that's only 50 builds. 

I think we should start looking at an alternative.
As GitHub actions is already running Test coverage (which effectively runs tests) we could also migrate the tests there..?

**Comment by PhilipVinc** [comment]
Travis today disabled CI for netket

**Comment by VolodyaCO** [comment]
gitlab is another good alternative. Their CI is apparently more robust than github actions.

**Comment by PhilipVinc** [comment]
Yep.
But as we basically already have tests running on Github Actions (because coverage essentially runs tests) i'm not going to switch.

@femtobit, Right now the Github Actions tests run CI with Jax on MacOS and Linux, and without Jax only on linux. I am inclined to keep this as is and be done with it. Maybe also add MacOS without jax.

As you are the person who wrote the travis script, I'd like to ask your opinion: do we still need all that convoluted Anaconda testing that is on travis? I don't really get the point of it, and right now Netket v3 is a very standard python source package so there is no reason it should not work on conda environments...

I think that we don't need to  am thinking of just getting rid of the whole conda thing from the

**Comment by femtobit** [comment]
@PhilipVinc Actually, I think @twesterhout wrote most of the current Travis config (including the anaconda part), so maybe he can tell you more about the history of the code there. I was not involved in that part too much.

Since I've personally very rarely used NetKet with conda, I am also not really in a position to give a qualified comment on whether we still need those tests or not. I do agree with your reasoning that without the C++ parts, current NetKet is a relatively normal Python package. The only complexity in setup would be to have mpi4py and jax working properly, but that should be taken care of already in a proper conda setup, so no particular reason to expect it to break specifically for NetKet.
On the other hand, personally, I would still prefer to keep one Anaconda test case (with JAX, if it's only one) as (a) I think it is a relatively common setup for people to run NetKet in and (b) since I am not using Anaconda myself at the moment, I might miss some unexpected bugs in that environment otherwise (though, as you say, this should be rare).

**Comment by gcarleo** [comment]
I would also try to keep a the tests within the conda environment, but hopefully this should be more or less standard to do within github actions?

**Comment by twesterhout** [comment]
I have a very positive experience with Github Actions so far. @PhilipVinc I don't have time right now to implement this, but feel free to ping me if you have any questions.

**Comment by PhilipVinc** [comment]
In the end we're using GitHub Actions.
We don't have conda tests but in my opinion we don't need them because netket is a simple python only package now.
