### ISSUE TITLE
[API] Duplicated functionality of graph

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#514]
From AbstractGraph:
```
    @property
    @abc.abstractmethod
    def n_nodes(self):
        r"""int: The number of vertices in the graph"""
        raise NotImplementedError

    @property
    def n_sites(self):
        r"""int: The number of vertices in the graph"""
        return self.n_nodes

    @property
    def n_vertices(self):
        r"""int: The number of vertices in the graph"""
        return self.n_nodes
```

I'd argye to keep only n_vertices, because it's the same terminology of networkx.

 - We are missing a function returning an iterator over vertices (they are not necessarily ordered, though usually so...)

 - The networkX api has edges as a property. For us it's a function. The only reason for this is because we want to be able to call edges(color=True), but that is only supported on some graphs.
I'd therefore argue to make all fields in graph properties, and graphs that support colors should just define a new method (colored_edges) that is an additional property.

**Comment by femtobit** [comment]
1. If I am not mistaken, NetworkX predominantly uses "nodes" as term in its API (such as in [`Graph.number_of_nodes()`](https://networkx.org/documentation/stable/reference/classes/generated/networkx.Graph.number_of_nodes.html#networkx.Graph.number_of_nodes), which is a bit too long for my tastes). So I suggest we standardize on `n_nodes`.

2. Adding `.nodes()` is definitely a good idea. I believe NetKet code now just assumes that all vertices are integers in `range(n_nodes)`. If we are changing this, we have to be careful to prevent bugs in current code when this assumption becomes invalid.

2. NetworkX has the somewhat exotic behavior where they return an `EdgeView` object from `.edges`, which is implemented so that `Graph.edges` and `Graph.edges()` both work (and, IIRC, behave differently which is a bit confusing). Our interface (with edges being a function) was meant to be similar to the NetworkX one, just without the added complexity of also allowing `.edges`. So I'd be slightly in favor of keeping `.edges()` as a function without splitting it. This also gives us the option of adding other properties (beside color) and exposing them via `.edges()`, similarly to NetworkX.

**Comment by gcarleo** [comment]
Can we close this?

**Comment by femtobit** [comment]
I think so.
