### ISSUE TITLE
Slowdown when using MPI on multiple cores

### ISSUE THREAD

**Issue by thorben-frank** [netket/netket#545]
Hi, 
I installed the master branch on my machine and observed that I get a slowdown when running the training on multiple cores. I was wondering if you have any idea where this comes from? 
Best
Thorben

**Comment by gcarleo** [comment]
Hi, we are in the process of stabilizing the APIs for the version 3.0 so maybe I would suggest that you wait a few days before fetching again from master/wait for a stable 3.0 release, the main activity is now happening in https://github.com/netket/netket/pull/539 (branch nk3)  

Maybe in the meanwhile if you have some specific benchmarks that shows this slowdown it would be useful for us to know, so that we can test it also against the nk3

**Comment by PhilipVinc** [comment]
Also, could you please tell me how you are running netket?  Is it a simple mpirun? How many MPI Processes are you using? 

See discussion in #464

**Comment by thorben-frank** [comment]
Sorry for my somewhat late reply.

**Edit note:** Updated my version of the branch v3.0 and now I observe the same behavior as in the master branch. So I removed the part in my original issue. 

I am running the following code: 

```
import netket as nk
import numpy as np
import json

L = 24
g = nk.graph.Hypercube(length=L, n_dim=1, pbc=True)

hi = nk.hilbert.Spin(s=0.5, N=L)

ha = nk.operator.Ising(hilbert=hi, graph = g, h=0.9)

#exact_result = nk.exact.lanczos_ed(ha)
#print(exact_result)
#exact_gs_energy = exact_result.eigenvalues[0]

#print("Exact energy is {}".format(exact_gs_energy))

ma = nk.machine.RbmSpin(hilbert=hi, alpha=2)#, automorphisms=g.automorphisms())
ma.init_random_parameters(seed=123, sigma=0.01)

sa = nk.sampler.MetropolisLocal(machine=ma)
#sa = nk.sampler.MetropolisHamiltonian(machine=ma, hamiltonian=ha)
#sa = nk.sampler.MetropolisExchange(machine=ma, graph=g)
#sa.delta_k = 1

op = nk.optimizer.Sgd(ma, learning_rate=0.01)

sr = nk.optimizer.SR(ma)
#lm = nk.optimizer.LM(ma, lsq_solver="IRAM")
# Stochastic reconfiguration
gs = nk.Vmc(
    hamiltonian=ha,
    sampler=sa,
    optimizer=op,
    n_samples=2000,
    sr=None,
#    lm=lm,
    )
```

I am running netket with 
```
mpirun -n $n_cores -x OMP_NUM_THREADS=1 python3 $file.py
```
so as I understand the solution in #464 won't fix the problem.

The times I recorded are the following:

- $n_cores = 1 | wall time = 169 s
- $n_cores = 2 | wall time = 167 s
- $n_cores = 3 | wall time = 173 s
- $n_cores = 4 | wall time = 184 s

**Comment by PhilipVinc** [comment]
Hi Thorben,

So... as @gcarleo has said, we are really-really near (let's say.. hopefully less than 2 weeks) from properly releasing a beta of the next netket version (what is in `nk3` branch right now). Lot's of things are changing... 

BTW, your example is missing the run line?

So it turns out that you are using `netket.machine.RbmSpin` that uses numpy under the hood. that will disappear, in favour of machines that use Jax . You can already find them in `netket.machine.Jax.RbmSpin`, I believe, or something like that. They are noticeably faster.

I don't really know what is going on in master with non-jax machines. It's weird, but as those will soon disappear I am not really inclined in investigating.

Testing an equivalent version ([see this gist](https://gist.github.com/PhilipVinc/9d300d4151b55a1c159812672a75f1ba)) of your script on what is nk3 branch (but should give somewhat similar results, though slower, on master with jax machines) I get the following timings:

```
➜ mpirun -n 1 -x OMP_NUM_THREADS=1 python test.py
100%|██████████| 500/500 [00:27<00:00, 18.48it/s, Energy=-28.858 ± 0.037 [σ²=2.299, R̂=1.0045]]

netket on  nk3 [$✘!?] via netket_env via 🐍 3.8.7 took 35s
➜ mpirun -n 2 -x OMP_NUM_THREADS=1 python test.py
100%|██████████| 500/500 [00:16<00:00, 29.55it/s, Energy=-27.144 ± 0.049 [σ²=3.727, R̂=1.0022]]

netket on  nk3 [$✘!?] via netket_env via 🐍 3.8.7 took 25s
➜ mpirun -n 3 -x OMP_NUM_THREADS=1 python test.py
100%|██████████| 500/500 [00:13<00:00, 37.90it/s, Energy=-28.665 ± 0.036 [σ²=3.035, R̂=0.9981]]

netket on  nk3 [$✘!?] via netket_env via 🐍 3.8.7 took 22s
➜ mpirun -n 4 -x OMP_NUM_THREADS=1 python test.py
100%|██████████| 500/500 [00:12<00:00, 39.69it/s, Energy=-28.839 ± 0.036 [σ²=2.024, R̂=1.0054]]
``` 

This is consistent with the fact that Jax machines don't use Numpy, but XLA, so `OMP_NUM_THREADS=1` is doing nothing. XLA is heavily parallelising operations under the hood. The flags to force single-threading are (poorly) documented in [Jax#743](https://github.com/google/jax/issues/743).

All this should be documented in the upcoming beta release.

**Comment by thorben-frank** [comment]
Hi Filippo,
you are right, I forgot to copy the line which contains the call to the run function. 

Thanks a lot for your comprehensive reply. Looking forward to the new netket version :-)
