### ISSUE TITLE
Typechecking user exposed functions/methods/constructors

### ISSUE THREAD

**Issue by VolodyaCO** [netket/netket#606]
In another [issue](https://github.com/netket/netket/issues/604#issuecomment-814287843) I proposed the use of [`typeguard`](https://typeguard.readthedocs.io/en/latest/userguide.html) to check static types of arguments in object constructors, or methods that are called only once.

This would simplify checking types internally, e.g.

```python
def foo(bar: int) -> int:
    assert isinstance(bar, int), "bar is not an int"
    ...
```

would simply change to 

```python
from typeguard import typechecked
@typechecked
def foo(bar: int) -> int:
    ...
```

Also, if there are some user exposed-only classes, the decorator `typechecked` can decorate the class, and it will check types of all of its methods when being used.

**Comment by gcarleo** [comment]
Wouldn't it be better to use mypy instead?

**Comment by PhilipVinc** [comment]
I'm curious about what @femtobit thinks.
However I'd put this on standby for a while because I am planning a large overhaul of hilbert and operator..

**Comment by gcarleo** [comment]
I would target full compatibility my mypy since (hopefully) we might even able to get some speed up using mypyc if types are correctly annotated

**Comment by PhilipVinc** [comment]
I don't think mypy will give us any speedup, as the performance-sensitive code is all numba or jax...

However, the two issues are orthogonal. Mypy will type-check our inner code before we do PRs and hopefully catch bugs.
 
What @VolodyaCO is proposing is to add decorators to functions so that if you pass the wrong type it raises an error immeditely if the type is wrong. This is more user-facing.

It would streamline some of our type checking that we do manually in some functions...
