### ISSUE TITLE
`QGTOnTheFly` is weirdly slow on a GPU

### ISSUE THREAD

**Issue by attila-i-szabo** [netket/netket#758]
@chrisrothUT has spotted a while ago that `QGTOnTheFly` is weirdly slow. To probe this, I've run two benchmarks for `QGTOnTheFly`, using
* [a dense feedforward network](https://github.com/attila-i-szabo/netket/blob/8f40a9e45eb0b36a0e924c9251c06b59bcde69b8/Benchmarks/qgt.py) 
* [a GCNN](https://github.com/attila-i-szabo/netket/blob/8f40a9e45eb0b36a0e924c9251c06b59bcde69b8/Benchmarks/qgt_gcnn.py)

both on my laptop (4 CPU cores) and a GPU cluster (1 K80 GPU). The first iteration takes a while in both cases because the solver has to be `jit`-compiled. On the CPU, the second run (with all inputs changed, as it would be in the VMC driver) is extremely fast (below 1 ms). On the GPU, however, it takes a time comparable to the first run, which suggests that either some of the jit-compilation happens every time or it ends up being very inefficient.

We don't know how to probe this further. As a quick fix, we could set `backend='cpu'` in the jit decorators in `QGTOnTheFly`, but it would be better to figure out why this happens.

**Output of the scripts:**

Dense, laptop:
```
First time took 9.841582 seconds
Second time took 0.000266 seconds
```
GCNN, laptop:
```
First time took 12.325909 seconds
Second time took 0.000301 seconds
```
Dense, GPU:
```
First time took 18.779504 seconds
Second time took 6.217923 seconds
```
GCNN, GPU:
```
First time took 131.027075 seconds
Second time took 120.383964 seconds
```

**Comment by femtobit** [comment]
> which suggests that either some of the jit-compilation happens every time or it ends up being very inefficient.

To make sure it's not the first of these alternatives, you could set the `JAX_LOG_COMPILES=1` environment variable. Then we know that part for sure.

**Comment by PhilipVinc** [comment]
And are you timing correctly according to jax lazy evaluation logic?

**Comment by chrisrothUT** [comment]
>To make sure it's not the first of these alternatives, you could set the JAX_LOG_COMPILES=1 environment variable. Then we know that part for sure.

I checked this and it is only compiling one time

**Comment by chrisrothUT** [comment]
> And are you timing correctly according to jax lazy evaluation logic?

@attila-i-szabo you want to run something like this: 
%time tree_map(lambda x: x.block_until_ready, qgt_.solve(cg, rhs1))
%timeit tree_map(lambda x: x.block_until_ready, qgt_.solve(cg, rhs2))

But yeah it still takes 1.7s on my P100 GPU. The CPU/GPU times aren't even close, so this issue is really bizarre.

**Comment by attila-i-szabo** [comment]
> > And are you timing correctly according to jax lazy evaluation logic?
> 
> @attila-i-szabo you want to run something like this:
> 
> ```
> %time tree_map(lambda x: x.block_until_ready, qgt_.solve(cg, rhs1))
> %timeit tree_map(lambda x: x.block_until_ready, qgt_.solve(cg, rhs2))
> ```

I think my timing is fine because I actually assign the output to the variable `lhs`. Also, nothing changed when I changed the code as @chrisrothUT suggested.

**Comment by PhilipVinc** [comment]
[No it’s not. ](https://jax.readthedocs.io/en/latest/async_dispatch.html#async-dispatch)

**Comment by PhilipVinc** [comment]
[~300 microseconds is roughly the dispatch time of Jax+flax ](https://github.com/google/flax/issues/912)

**Comment by chrisrothUT** [comment]
> Also, nothing changed when I changed the code as @chrisrothUT suggested.

In any case, I think it's pretty clear there's an issue on the GPU. The JVP and VJP parts of the algorithm should be very GPU friendly so my guess is there's a process that is serialized that is slow on the GPU and negligible on the CPU. 

>We don't know how to probe this further. As a quick fix, we could set backend='cpu' in the jit decorators in QGTOnTheFly, but it would be better to figure out why this happens.

Yeah, I'm not even sure this is a useful hack because it takes a lot of time to move tensors back and forth.

**Comment by PhilipVinc** [comment]
Anyhow, the scaling of the compilation time is surprising (can you run the cpu code on the same machine with gpu?)
It should be somehow comparable.

Also, can you rerun your timings with `OnTheFly(centered=False)` and add those timings to your list? 
I might have an idea of what is causing issues.

--
It's might also be a jax codegen bug.
Jax devs are quite responsive (they fixed all bugs I reported in 2-3 weeks), but you have to put together a decent MWE, otherwise they ignore them.

Doing that for something as complex as our QGTOnTheFly will probably require a few hours.
If you are willing and have the time I can help you do that.

Roughly, you need to properly benchmark (aka, run things 10-1000 times, not once, with `%timeit`, for example ) the forward pass and a reverse (`vjp`) pass on the model on the same machine, with the latest version of jax and jaxlib.
You should time things both on CPU and GPU.

Set up the model without using netket. just create random matrices for samples and everything else.

Then you should copy-paste the code of QGTOnTheFly, only the parts that we need and try to condense it a bit and time that.

**Comment by PhilipVinc** [comment]
I would focus on the Dense case, as it's easier.
And I would try to study how the compilation time  and runtime of QGTOnthefly scales on CPU and GPU with increasing number of layers. 
I suspect something bad is happening there

**Comment by attila-i-szabo** [comment]
> [No it’s not. ](https://jax.readthedocs.io/en/latest/async_dispatch.html#async-dispatch)

OK, thanks for this. Turns out things are actually the right way around:
```
First time took 11.654447 seconds
Second time took 4.709227 seconds
centered=False, GPU
```
```
First time took 18.370595 seconds
Second time took 6.245057 seconds
centered=True, GPU
```
```
First time took 137.27048 seconds
Second time took 133.450531 seconds
centered=False, pure CPU
```
```
First time took 147.390808 seconds
Second time took 131.930185 seconds
centered=True, pure CPU
```
By "pure CPU" I mean running the code on a single CPU core of the same cluster, without access to GPU. Interestingly, having a GPU around but jitting the solver with `backend='cpu'` is faster, but still way slower than doing everything on the GPU:
```
First time took 102.220755 seconds
Second time took 96.709239 seconds
centered=False, CPU
```
```
First time took 111.299072 seconds
Second time took 97.937808 seconds
centered=True, CPU
```
It's a bit strange that `centered=False` leads to no appreciable speedup on the CPU, but we get the expected factor of 1.5 on the GPU. Also, it's odd that the asynchronous dispatch only kicks in on the GPU.

I think if there is anything to be solved here, it's speeding up the GCNN, but that's not for this issue. If you agree, we can close this, apologies for the noise.

> @attila-i-szabo you want to run something like this:
> 
> ```
> %time tree_map(lambda x: x.block_until_ready, qgt_.solve(cg, rhs1))
> %timeit tree_map(lambda x: x.block_until_ready, qgt_.solve(cg, rhs2))
> ```

@chrisrothUT there is a small but very important error in this: it should be `block_until_ready()` not `block_until_ready` – the latter won't block anything.

**Comment by attila-i-szabo** [comment]
BTW, [here](https://github.com/attila-i-szabo/netket/blob/5044b3fbec21216c6a1408a01137f8e2992b7c5d/Benchmarks/qgt.py) is the fixed benchmark

**Comment by PhilipVinc** [comment]
> but still way slower than doing everything on the GPU:

you mean on the CPU?

**Comment by attila-i-szabo** [comment]
No. If the timing is done properly, GPU is much faster than everything else.

**Comment by PhilipVinc** [comment]
Ah, yes. Now i understand.
This is only the FFNN, right?

Anyhow, that's good.
Turns out there are no issues at all.

> Interestingly, having a GPU around but jitting the solver with backend='cpu' is faster, but still way slower than doing everything on the GPU:

That's curious, but  i'd properly benchnmark by running the 'second time' 5 times before being sure about that...
I also don't know how `backend=cpu` plays with nested jit blocks.
Probably it all runs on cpu (because you cannot mix cpu and gpu in a single jit block) but maybe something else is happening.
Or it generates different code for some weird reason.

> It's a bit strange that centered=False leads to no appreciable speedup on the CPU, but we get the expected factor of 1.5 on the GPU. Also, it's odd that the asynchronous dispatch only kicks in on the GPU.

Yes. centered gives an extra jvp (forward diff) call, IIRC, so you get a bunch of extra operations. 
This probably means that we are overhead-bound on the GPU, that is, it means that the matmuls we are doing on the GPU are relatively small and therefore the time taken to dispatch one is higher than the time it takes to actually perform it. 
(On the GPU you have 3 levels of dispatch time, if you want. The jax one, scheduling calls to CUDA, the time taken to move data and instructions to GPU, if necessary, and the time taken by the GPU to properly start a subrouting like matmul.)
On the cpu the 2 lower levels are absent.

We could verify this by profiling with NVIDIA tools but, whatever.

**Comment by attila-i-szabo** [comment]
> This is only the FFNN, right?

Here are the equivalent benchmarks for the GCNN:
```
pure CPU
First time took 4881.857042 seconds
Second time took 5033.897782 seconds
```
```
GPU
First time took 133.234154 seconds
Second time took 119.72073 seconds
```
These both use `centered=True`, I can't be bothered to run it with `False`.

> I also don't know how `backend=cpu` plays with nested jit blocks.

That's not a concern here, the only places we jit are `_solve` and `_matmul`, I set both of those to `backend=cpu`

**Comment by chrisrothUT** [comment]
> That's not a concern here, the only places we jit are _solve and _matmul, I set both of those to backend=cpu

I don't think this is worth it. When I run a full optimization loop with these setting the expect_and_grad takes way more time. Not sure if expect_and_grad is jax defaults to run everything on the CPU or it just takes a ton of time to copy the data back and forth. 

> By "pure CPU" I mean running the code on a single CPU core of the same cluster

I'm still confused, what was the deal with the really fast performance on the CPU before? I ask because it seemed to run very fast in real time as well. Was it just not doing the computation? (It did seem suspiciously fast tbh)

**Comment by attila-i-szabo** [comment]
> I'm still confused, what was the deal with the really fast performance on the CPU before? I ask because it seemed to run very fast in real time as well. Was it just not doing the computation? (It did seem suspiciously fast tbh)

In this benchmark, it didn't do the computation. If you just write `qgt_.solve`, it dispatches but doesn't stop until the output is needed; if you write `x.block_until_ready`, that's a function, so you can get that lazily too; you have to write `x.block_until_ready()` to actually force the computation. 

And it seems it does get a lot slower in the full VMC loop.
