### ISSUE TITLE
[Design] Continuous Systems

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#802]
Since it has been decided that soon our fellow @gpescia will contribute code for continuous systems, i'd like to take a moment to design how this should work, notably at the level of hilbert and samplers.

For particles in continuous space, we essentially want to express the following informations:
 - type of particle (boson/spinboson/fermion)
 - the space (R, R2, R3), or size +dimensions of the box.
 - boundary conditions? PBC/Hard (i'm not sure this is the right place to put them.)
 - might also include an optional discretization factor so that exact solvers can work ?

If we also include the discretization factor in the hilbert space, than we can still convert operators defined on such an hilbert space to dense matrices with no issues, otherwise the `to_dense` method will need to take extra arguments.

I think that the size of the _box_ belongs to the hilbert space, because it's necessary to generate randomk states correctly.

Samplers can `read` this informations and use it to generate random states and transitions.
If the boundary informations (PBC/Hard) are included in the hilbert space, no extra informations should be provided to the sampler other than the hilbert space in order for simple transition kernels to work.
If the bounary information is not specified in the hilbert, the transition kernel must know whever we have PBC (and so wrap around moves that fall out of the box) or if it should truncate the probability in order not to propose transitions outside the box.

So it seems to me that the best would be to put such information in the hilbert.

If the discretization is in the hilbert, we could have the ExactSampler work automatically too, otherwise, this would need extra arguments too.
(I kind of like the idea that the same code would work for discrete and continouus systems provided one changes the hilbert and operators).

cc @gcarleo

**Comment by gcarleo** [comment]
Yes, I agree I guess with most of it! I would propose something like 
```nk.hilbert.Particles(N=10, L=(3,3,3), pbc=(True,True,False),type="boson")```

or something like that (this would be for canonical simulations at N fixed, there might be another hilbert or an additional ```mu=...``` to set up the chemical potential for other simulations in the grand canonical. 

(notice that the dimension can be inferred directly from the tuple size). 

To be honest, the really clean interface would be to pass a ```Geometry``` argument to particles, in case we would like to do particles in boxes that are not hypercubic etc 
```nk.hilbert.Particles(N=10,geometry=nk.graph.Hypercube(...),type="boson") ```, but this seems a bit redundant maybe, I am not sure one often needs to do weird geometries in continous space. 



Concerning the discretization, things are quite tricky there because there are many different ways of setting up a discrete basis given a continous hamiltonian, so I would actually put the discretization (or maybe several options to discretize) in the Hamiltonian itself, not in the Hilbert. In any case this point is quite important but needs more thought, I would maybe think about this at a later stage.

**Comment by PhilipVinc** [comment]
Fair enough.
I think we could add `geometry` kwarg later on.
Ideally we would come up with an interface to geometry now, but let's leave it for later.

Once #800 is merged (i think it's ready to go) @gpescia could contribute the code for hilbert and the samplers

**Comment by gcarleo** [comment]
ok great, I approved that pr

**Comment by gpescia** [comment]
I added a PR in #808 adding the continuous hilbert and a sampler rule for continuous hilbert.
