### ISSUE TITLE
AbstractVariationalDriver.py bug in updating step_count

### ISSUE THREAD

**Issue by evmckinney9** [netket/netket#816]
![image](https://user-images.githubusercontent.com/47376937/125520970-8a189955-4de6-45b2-acfc-45eab4c82d9e.png)

I think this error can be fixed either by writing a setter function for the `@property step_count` in the same way that `@optimizer.setter` exists in the same file. 

Otherwise, maybe this can be fixed by changing ` self.step_count = 0` to ` self._step_count = 0`.

![image](https://user-images.githubusercontent.com/47376937/125521480-ca41de24-c283-4d8c-bf16-ba25a93b2399.png)

**Comment by PhilipVinc** [comment]
Oh. Wow.
I think this happens because we don't test .reset()...

The right way to do this is to change the internal field. It's not supposed to be set explicitly...

Do you want to open a quick PR? I'll tag a release right after.

**Comment by evmckinney9** [comment]
I'm not super sure that this actually fixes the issue. I have a trained model and need to restart the jupyter notebook in order to reproduce the same graphs. Before, the error was obvious because the iterations did not start at 0 on my plot of the structure factor. Now, it starts and 0 but the graph is not the same after calling gs.reset() as actaully restarting the notebook and running it fresh.

**Comment by gcarleo** [comment]
this might be because you are not resetting the parameters in the model, I believe reset will reset only the internal step of VMC not the model itself, maybe we should discuss this in the docs a bit better...

**Comment by PhilipVinc** [comment]
@evmckinney9 I pushed a new release with yuour fix. Thanks again for the report and the PR.

In any case, as giuseppe was mentioning, `vmc.reset()` basically only resets the internal counter used to log data. It does not reset the variational state, because the reset there is ill defined (what should it do? reset to the initial parameters? reset to random state?) so if you want to `reset` the state, it's best to create a new one (or call `vstate.init()`, i think)
