### ISSUE TITLE
No mpi_available ? 

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#826]
>>> print (netket.utils.mpi_available)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'netket.utils' has no attribute 'mpi_available'

**Comment by PhilipVinc** [comment]
When mpi became a module I think I moved it there.
It is now netket.utils.mpi.mpi_available (could be renamed available).

I re-exported utils.mpi4jax_available but I did not re-export mpi_available probably because the former was not used anywhere (note that in netket 3 the two coincide because we error if only mpi4py is installed).

I think the cleanest fix would be to rename utils.mpi.mpi_available to mpi.available in utils/mpi/init.py
Il 19 lug 2021, 09:29 +0200, Giuseppe Carleo ***@***.***>, ha scritto:
