### ISSUE TITLE
Naming for continous things

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#859]
It seems that we now have `hilbert.ContinuousBoson` and we will have likely also `hilbert.ContinuosFermion`. Personally I think that these names are not good and should be changed. The main reason is that we will have that only continous systems have a specifier in their name wherease lattice systems dont (i.e. we do not have `hilbert.DiscreteFock` or something) 

I also don't know what an elegant solution might be, but let me put some here 

1. `nk.particle.Boson`,`nk.particle.Fermion` etc, where things in particle are continuous 
2. `nk.hilbert.continuous.Boson` etc also implying `nk.hilbert.discrete.Spin` etc 
3. `nk.hilbert.Boson` and `nk.hilbert.Fermion` implying these are continous objects by construction and no ambiguity arises with Fock objects (but what about lattice fermions?) 
4. we specify the statistics at construction time `nk.hilbert.Particle` will have a keyword `type=boson` or something similar 

The cleanest is 2, but it is breaking and requires too many words... I think 4 is a good compromise, and that's what we were actually discussing during the PR, not sure why it was not done eventually

**Comment by gcarleo** [comment]
notice that this would also imply that `Fock` has a `type` in the constructor for fermions

**Comment by PhilipVinc** [comment]
As i had stated previously, I'm not against option 4.
I simply want the resulting object (fermion/boson/whatever) to be its own type.
A bit like right now when you call `DenseSymm(mode=`full/fft`)` that is a function, and depending on `mode` you get a type or another (`DenseSymmFull/DenseSymmFFT`).

I don't know if that will be usefull or not. It allows us to dispatch on the type of the hilbert space.
Maybe it will be useless.
But it might  not be . We might need it in some algorithms or samplers to differentiate between the two cases.
And i'd rather not limit our posisbilities when this has literally no cost on code-complexity or anything.

This can be done with
```python
def nk.hilbert.Particle(*args, mode, **kwargs):
   if mode=="boson":
       return ContinuousBoson
   elif mode=="fermion":
       return ContionuousFermion
```

--

Regardless, I'm kind-of against such approach from a user-api point of view.
Because I find tab-completion (`nk.hilbert.[\tab\tab]`, `nk.hilbert.Cont[\tab\tab]`) much easier to discover a package than checking the docstrings for `nk.hilbert.Particle` or running it once and seeing an error that `type has not been specified` or `type should be boson and not bosons` or whatever else.

--

About the discrepancy with discrete systems: is this an issue? the fock space for fermions has `n_particles=1` so if you want fermions on a lattice you have an extra argument anyway. One more reason to make it a different object, in my opinion.

Anyway, the current API is there for historical reasons. I'd wait to see what issues arise with fermions on discrete systems before changing it...

**Comment by gcarleo** [comment]
It's just that `ContinousBoson` is a bad name, what is continous? the boson itself or the space? why the Spin is not `DiscreteSpin` etc... that is my only issue here

**Comment by gpescia** [comment]
We could put `ContinuousSpaceBoson` but that is also crazy long..

**Comment by PhilipVinc** [comment]
> It's just that ContinousBoson is a bad name, what is continous? the boson itself or the space? 

What does it mean for the boson itself to be continuous? To be in the phase space representation? But then i'd call it `PhaseSpace` or more properly `WignerRepr` `PRepr`, `QRepr` depending on which representation is chosen... I don't personally see the potential for confusion.

> why the `Spin` is not `DiscreteSpin` etc... that is my only issue here

Because that would be a (useless?) breaking change?

**Comment by gcarleo** [comment]
There's a problem of internal consistency of the APIs if you have
ConyinpusBoson you expect to have also DiscreteStuff otherwise you are
introducing an asymmetry in the naming.

Bosons can be continuous but be on a lattice... For example if you have a
rotor model etc.

**Comment by PhilipVinc** [comment]
>ConyinpusBoson you expect to have also DiscreteStuff otherwise you are

I understand, but it makes no sense to break the old api, which for a while will still be the main use-case of netket, doesn't it?

>Bosons can be continuous but be on a lattice... For example if you have a rotor model.

I'm not very familiar with the rotor model, but from what I recall that is the model where you are trying to describe N coupled `rotors` which are described by the direction where the rotor is pointing at?

So every rotor lives on the surface of a sphere?

**Comment by gcarleo** [comment]
Indeed I am not proposing to break the old APIs, I also think it's bad to
have DiscreteFock or something. I'm saying that if you do ContinuousBoson
makes things asymmetric between lattice and cotninous space, introducing
extra naming only for continuous variables. I'm trying to find a solution
that avoids doing that... That's why solution 2 is the cleanest and more
symmetric, but it'ss too verbose... maybe doing just Boson after all is not
too bad

**Comment by gcarleo** [comment]
Mmmm ok, thenthe future  LatticeBoson and LatticeFermion seem the natural
way to balance ContinuousBoson

**Comment by gcarleo** [comment]
Yes every rotor is an angle variable essentially

**Comment by PhilipVinc** [comment]
But then this is well described by VpntinuousBoson anyway, it’s just that you shouldn’t interpret it as a spatial dimension (and interaction won’t be due to physical distance) but it should be interpreted as an angle, and the interaction term must know about the graph/lattice.

I think it all makes sense whitin yhe current framework…
Il 11 ago 2021, 18:19 +0200, Giuseppe Carleo ***@***.***>, ha scritto:
> Yes every rotor is an angle variable essentially
>
