### ISSUE TITLE
Constrained Hilbert Does Nothing

### ISSUE THREAD

**Issue by chrisrothUT** [netket/netket#931]
NetKet allows you to define a Hamiltonian on a constrained Hilbert space using something like

```
hi = nk.hilbert.CustomHilbert(constraint_fn=constraint_fn,...)
ha = nk.operator.Heisenberg(hilbert=hi,...)
```

where `constraint_fn` is a function that returns a bool if the states are in the Hilbert space. However, none of the methods that find the connected elements of the Hamiltonian pay any attention to these constraints.

**Comment by PhilipVinc** [comment]
This is/was by design.
`constraint_fn` only affects `hilbert.random_state`, that is, the generation of random states from the hilbert space.
Implemented Operators don't really consider what states are not part of the hilbert space.
That's because it would be relatively costly to do so and if the operator already respects the constraint (that is, valid states are only connected to valid states) that would be useless.

We could add a switch, though.

Or you can write your own operator that does that.

**Comment by femtobit** [comment]
> Or you can write your own operator that does that.

This is the way. A `Heisenberg` operator respecting additional constraints (i.e., has fewer matrix elements) is not actually the Heisenberg model anymore, so it would be confusing, IMHO, if operators just silently accepted additional constraints.

We had some discussion on whether to warn users about constraints not being respected in relation to #853. But that is hard to detect, except in simple cases.

**Comment by chrisrothUT** [comment]
Okay, thanks for the information!
